"""empty message

Revision ID: 36ef4f37a66d
Revises: 9f85d04758b6
Create Date: 2026-02-24 01:37:50.739412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36ef4f37a66d'
down_revision = '9f85d04758b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_games', sa.Text(), nullable=True))
        batch_op.drop_column('favorite_game')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_game', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('favorite_games')

    # ### end Alembic commands ###
