"""Ajout du champ is_active

Revision ID: 3f94ccfb50b0
Revises: 57eaf29366eb
Create Date: 2026-02-19 12:58:25.573685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f94ccfb50b0'
down_revision = '57eaf29366eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
