"""Ajout colonne created_at pour les reservations

Revision ID: 4778045a4e9a
Revises: 36ef4f37a66d
Create Date: 2026-02-26 14:33:49.407183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4778045a4e9a'
down_revision = '36ef4f37a66d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
