"""Ajout colonne image_url pour Cloudinary

Revision ID: 57eaf29366eb
Revises: a7dca1806139
Create Date: 2026-02-19 12:04:58.489123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57eaf29366eb'
down_revision = 'a7dca1806139'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
