"""Ajout colonnes profil utilisateur

Revision ID: 9f85d04758b6
Revises: 3f94ccfb50b0
Create Date: 2026-02-24 01:29:06.288924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f85d04758b6'
down_revision = '3f94ccfb50b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('favorite_game', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('favorite_game')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
