"""Ajout de la colonne price_per_hour

Revision ID: a7dca1806139
Revises: cdce77650dd4
Create Date: 2026-02-19 11:08:23.654209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7dca1806139'
down_revision = 'cdce77650dd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_per_hour', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.drop_column('price_per_hour')

    # ### end Alembic commands ###
